<script language="javascript">
	function slmenu(url){
		
		window.location = url;
	}
	
	
</script>
<form name="chonlua">
<p align="right"><select name="chon" onChange="slmenu(this.value)">
					
					<option value="danhsach_chitietthongtin.asp">Danh sách chi tiết thông tin</option>
					<option value="danhsach_chitiettochuc.asp">Danh sách chi tiết tổ chức</option>
					<option value="danhsach_diemtieuchuanmoitruong.asp">Danh sách điểm tiêu chuẩn môi trường</option>
					<option value="danhsach_hieuquacongnghekythuat.asp">Danh sách hiệu quả công nghệ kỹ thuật</option>
					<option value="danhsach_hieuquacongnghethongtin.asp">Danh sách hiệu quả công nghệ thông tin</option>
					<option value="danhsach_hieuquacongnghetochuc.asp">Danh sách hiệu quả công nghệ tổ chức</option>
					<option value="danhsach_nhantoconnguoi.asp">Danh sách nhân tố con người</option>
					<option value="danhsach_nhantomoitruong.asp">Danh sách nhân tố môi trường</option>
				</select></p>
				
</form>